"""Conteúdo autoral do curso. Exemplos e números de exercícios são fictícios."""
FONTES = {
 'dgm': ('Darwin Gödel Machine — Sakana AI, 2025', 'https://sakana.ai/dgm/'),
 'dgmp': ('Darwin Gödel Machine — artigo científico', 'https://arxiv.org/abs/2505.22954'),
 'alpha': ('AlphaEvolve — Google DeepMind, 2025', 'https://deepmind.google/blog/alphaevolve-a-gemini-powered-coding-agent-for-designing-advanced-algorithms/'),
 'intern': ('Aceleração da pesquisa — OpenAI, 2026', 'https://openai.com/index/research-acceleration-view-inside-openai/'),
 'standards': ('Padrões para a próxima fase da IA — OpenAI, 2026', 'https://openai.com/index/building-standards-next-phase-ai/'),
 'dsec': ('DSec — estudo da DeepSeek, 2026', 'https://arxiv.org/abs/2609.22978'),
 'science': ('AI Scientist — publicação em oficina científica, 2025', 'https://sakana.ai/ai-scientist-first-publication/'),
 'reward': ('Modelos que produzem sua própria recompensa — ICML 2024', 'https://arxiv.org/abs/2401.10020'),
 'collapse': ('Treino recursivo com dados gerados — estudo dos autores', 'https://arxiv.org/abs/2305.17493'),
 'metr': ('Limitações do horizonte de tarefas — METR, 2026', 'https://metr.org/notes/2026-01-22-time-horizon-limitations/'),
 'tamper': ('Manipulação da recompensa — Anthropic, 2024', 'https://www.anthropic.com/research/reward-tampering'),
 'epoch': ('O debate precisa de experimentos — Epoch AI', 'https://epoch.ai/gradient-updates/the-software-intelligence-explosion-debate-needs-experiments'),
}
# step: título, explicação, exemplo profissional, rótulo A, conteúdo A, rótulo B, conteúdo B
AULAS=[]
def aula(titulo,promessa,dor,resumo,termo,definicao,steps,pratica,molde,checks,gabarito,quiz,cartoes,extra,fontes):
 AULAS.append(dict(titulo=titulo,promessa=promessa,dor=dor,resumo=resumo,termo=termo,definicao=definicao,steps=steps,pratica=pratica,molde=molde,checks=checks,gabarito=gabarito,quiz=quiz,cartoes=cartoes,extra=extra,fontes=fontes))

aula('RSI: quando melhorar também melhora o próximo ciclo',
'classificar três situações e reconhecer o que seria melhoria recursiva.',
'Uma resposta melhor impressiona. Mas isso não revela se a IA aprendeu a melhorar a si mesma. Comece descobrindo o que realmente mudou.',
['Repetir uma tarefa não é melhorar o sistema.','Uma mudança precisa sobreviver a uma comparação.','Na recursão, a melhoria alimenta a capacidade de melhorar.'],
'RSI','Autoaperfeiçoamento recursivo: melhorias no sistema ajudam a produzir novas melhorias. A sigla vem do inglês recursive self-improvement.',[
('A pergunta é o que mudou','Uma IA pode reescrever uma mensagem sem alterar seu funcionamento. Pode também propor uma nova regra de trabalho, guardada para usos futuros. São mudanças diferentes. Para falar em recursão, procure evidência de que a nova versão ajuda a melhorar as próximas versões.', 'gestora|Na papelaria fictícia de Marina, encurtar uma resposta muda o texto. Guardar um procedimento de comparação muda o trabalho futuro.', 'Texto revisado','A mensagem ficou mais curta. O procedimento continua igual.','Processo revisado','Toda proposta passa por uma comparação antes de virar regra.'),
('Melhorias locais têm valor','Você pode aproveitar ciclos de melhoria sem construir uma IA autônoma. Neste curso, as práticas são experiências supervisionadas. Elas ensinam a propor, comparar e decidir. Não demonstram uma explosão de inteligência nem alteram automaticamente o modelo usado no chat.', 'educador|Ícaro, educador fictício, compara instruções para criar exercícios. Ele guarda a melhor instrução, mas não afirma ter treinado uma nova IA.', 'Pedido vago','Melhore meu jeito de preparar exercícios.','Pedido verificável','Compare duas instruções usando os mesmos três textos. Conte perguntas respondíveis só com cada texto.'),
('O ciclo precisa de evidência','Uma versão que se elogia não comprova melhoria. Registre a versão anterior, o teste, o resultado e quem decidiu. Separe capacidade em uma tarefa da capacidade de fazer pesquisa. Mais velocidade numa etapa pode não mudar o desempenho do conjunto.', 'gestora|Marina mantém a resposta antiga e a nova. Só troca a orientação depois de testar perguntas que não usou na revisão.', 'Pergunta de controle','Qual parte do sistema mudou?','Evidência necessária','A nova versão melhora resultados e ajuda a produzir melhorias futuras?')],
'Separe três situações',
'Anote no papel ou no bloco de notas.\nA: a IA reescreveu uma resposta.\nB: a IA propôs uma regra; uma pessoa testou e guardou.\nC: um sistema mudou seu método de pesquisa; novas versões produziram melhorias verificadas.\nClassifique: revisão de resposta, melhoria supervisionada ou indício de recursão. Explique o que ainda falta medir.',
['Classifique A, B e C sem consultar a resposta.','Escreva qual objeto mudou em cada situação.','Compare com o gabarito e corrija uma justificativa.'],
'A revisa a resposta. B melhora um procedimento sob supervisão. C sugere recursão, mas exige testes independentes e repetidos. Nenhum caso prova aceleração ilimitada.',
('Uma ferramenta ficou melhor em resumir. Isso comprova RSI?','Ainda falta evidência.','Sim, qualquer ganho prova.','Sim, se o texto agradou.'),
[('Você ajustou uma frase no chat. O que mudou?','O texto produzido; isso não demonstra mudança no mecanismo de melhoria.'),('Uma nova versão propõe bons experimentos. O que falta conferir?','Se os experimentos produzem ganhos verificáveis e transferíveis, comparados à versão anterior.'),('Como usar esta ideia numa escola?','Teste pequenas mudanças de instrução e preserve a decisão humana.')],
('Três níveis de afirmação','Autoaperfeiçoamento é um termo amplo. Aqui distinguimos revisão da resposta, melhoria do sistema e melhoria da capacidade de melhorar. Essa divisão é didática. Não é uma classificação universal da área. Sistemas reais podem misturar essas camadas. Observe qual componente foi alterado e qual resultado foi medido. Uma boa análise descreve o mecanismo antes de atribuir um rótulo.'),['dgm','standards'])

aula('Resposta, memória e treinamento mudam coisas diferentes',
'identificar quatro formas de melhorar um sistema e escolher uma para uma tarefa simples.',
'Uma conversa parece aprender com você. Essa impressão pode vir apenas das mensagens anteriores. Identificar a camada evita esperar uma mudança que não aconteceu.',
['Contexto orienta a resposta atual.','Memória guarda informação para ser recuperada.','Treinamento altera os parâmetros do modelo.'],
'parâmetros','Valores internos ajustados durante o treinamento. Não são as mensagens que você escreve numa conversa.',[
('Contexto é o material desta tentativa','O modelo responde usando instruções e informações disponíveis. Uma correção na conversa pode mudar a próxima resposta. Isso não significa que seus parâmetros foram atualizados. Ao começar outra conversa, parte desse material pode deixar de estar disponível.', 'educador|Ícaro cola um pequeno texto sobre reciclagem antes de pedir perguntas. A resposta melhora porque recebeu a referência necessária.', 'Sem referência','Crie perguntas sobre a atividade de hoje.','Com referência','Use este texto: papel limpo vai para reciclagem; papel engordurado exige outra destinação.'),
('Memória precisa ser consultada e conferida','Guardar uma regra ajuda apenas quando o sistema a recupera no momento certo. A regra pode envelhecer ou contradizer outra. Dê nome, data e responsável ao registro. Antes de usar uma informação importante, confirme se ela ainda vale.', 'gestora|Marina mantém a orientação de atendimento num documento. Ao mudar o horário da loja, atualiza a orientação e confere respostas antigas.', 'Registro incompleto','Atendemos até tarde.','Registro útil','Horário de exemplo: 9h às 18h. Conferir a versão vigente antes de responder.'),
('Treinamento é outra intervenção','Treinar ajusta os parâmetros com exemplos ou sinais de avaliação. Trocar ferramentas ou instruções pode melhorar o sistema sem esse ajuste. Comece pela camada mais simples que resolve o problema. Não use treinamento para compensar uma referência ausente.', 'educador|Ícaro quer que as perguntas citem o trecho de apoio. Primeiro muda a instrução e mede; não precisa começar treinando um modelo.', 'Mudança leve','Fornecer referência e pedir evidência.','Mudança profunda','Ajustar parâmetros com dados e avaliação especializada.')],
'Escolha a camada adequada',
'Caso da loja: a IA informa um horário antigo.\nCaso da escola: a IA cria questões sem receber o texto.\nCaso de pesquisa: um laboratório ajusta parâmetros com exemplos avaliados.\nPara cada caso, escreva o que falta e qual camada precisa mudar.',
['Diferencie informação ausente de informação desatualizada.','Associe cada caso a contexto, memória ou treinamento.','Justifique por que uma intervenção menor pode bastar.'],
'Loja: atualizar a referência recuperada. Escola: fornecer o texto no contexto. Laboratório: treinamento. Não há motivo suficiente para treinar nos dois primeiros casos.',
('Você abriu outra conversa e a regra sumiu. Qual hipótese testar?','Faltou contexto recuperado.','O modelo perdeu parâmetros.','Todo treinamento foi desfeito.'),
[('Uma regra salva garante que será seguida?','Não. Ela precisa ser recuperada, estar atualizada e ser testada.'),('Um ajuste de instrução muda os parâmetros?','Não necessariamente; normalmente muda o contexto usado na resposta.'),('Qual camada escolher quando falta um documento?','Fornecer a referência antes de considerar intervenções mais caras.')],
('Aprender durante o uso','Alguns sistemas combinam memória, ferramentas e treinamento posterior. Portanto, evitar a frase “o chat aprende tudo” é mais preciso que dizer “IA nunca aprende”. Pergunte o que foi persistido e como entrou no próximo uso. Em sistemas profissionais, documente a origem e a validade de cada memória. Uma anotação falsa recuperada muitas vezes pode espalhar o mesmo erro.'),['reward','collapse'])

aula('Leia uma notícia sem transformar previsão em fato',
'preencher uma ficha de evidência para uma afirmação sobre RSI.',
'Notícias misturam resultados, metas e interpretações. Um número sem contexto pode parecer uma prova muito maior do que realmente é.',
['Procure o documento original.','Registre o que foi medido e por quem.','Metas e cenários continuam sendo possibilidades.'],
'evidência','Registro que permite conferir uma afirmação. Pode ser um experimento, sua medida e suas condições.',[
('Comece pela afirmação exata','Separe uma frase verificável da opinião que a acompanha. Procure o estudo ou relato original, sua data e seus autores. Um vídeo pode apresentar boas ideias, mas sua narração não substitui o documento. Registre também se houve avaliação externa.', 'gestora|Marina lê “a IA faz toda a pesquisa”. Ela procura quais tarefas foram feitas e quais decisões permaneceram humanas.', 'Frase ampla','A IA substituiu toda a pesquisa.','Pergunta concreta','Quais etapas foram automatizadas, em qual experiência?'),
('Atividade não é resultado final','Mais horas de execução ou mais experimentos não medem diretamente descobertas úteis. Em setembro de 2026, a OpenAI relatou maior uso interno de agentes. Também afirmou que pessoas ainda escolhem prioridades e decidem quais resultados perseguir.', 'educador|Ícaro pode gerar cem exercícios numa tarde. Isso não informa quantos são corretos ou ajudam seus alunos.', 'Contagem de atividade','Quantidade de exercícios gerados.','Medida de utilidade','Quantidade de exercícios corretos e adequados ao objetivo.'),
('Escreva o limite junto do resultado','Uma experiência pode ter poucos casos ou tarefas muito específicas. Um cenário futuro é uma ferramenta para discutir possibilidades. Não vira calendário garantido. Use três etiquetas no seu registro: observado, interpretação e previsão. Deixe o que não conseguiu verificar explicitamente em aberto.', 'gestora|Marina aceita testar uma nova rotina. Não muda toda a empresa por causa de uma previsão de prazo.', 'Observado','Resultado descrito e suas condições.','Em aberto','Se o ganho se repete em outras tarefas ou organizações.')],
'Faça uma ficha de evidência',
'Abra uma fonte do material complementar.\nAnote: título; data; autores; afirmação principal; medida; comparação; limite.\nEscreva uma frase começando por “A fonte relata…”.\nEscreva outra começando por “Isso ainda não demonstra…”.',
['Localize o documento original e sua data.','Separe uma medida de uma interpretação.','Registre uma limitação sem inventar conclusões.'],
'No relato da OpenAI, o marco é definido e avaliado pela própria organização. Ele descreve tarefas sob direção humana. Isso não comprova autonomia integral.',
('Uma empresa anuncia uma meta para 2028. Como registrar?','Como meta anunciada.','Como resultado confirmado.','Como prazo científico certo.'),
[('Um gráfico mostra dez vezes mais tentativas. O que ele não garante?','Dez vezes mais descobertas válidas ou qualidade dez vezes maior.'),('Qual origem procurar após assistir a uma notícia?','O documento primário citado, com data e condições.'),('Como registrar uma informação sem confirmação?','Como não verificada, sem usá-la como premissa factual.')],
('Análise do material de origem','O projeto RSI reúne três transcrições em alemão, uma interpretação do usuário e duas pesquisas anteriores. O curso preserva a ideia de avaliar ciclos. Algumas passagens apresentam vazamentos e comparações sem condições completas. Elas não entram como resultados comprovados. Números de modelos comerciais foram dispensados quando não ajudam a entender o mecanismo. A pesquisa completa e a decisão editorial estão na documentação deste curso.'),['intern','metr'])

aula('Desenhe o ciclo antes de automatizar',
'montar uma ficha com as oito etapas de um ciclo de melhoria supervisionada.',
'Pedir “melhore continuamente” deixa quase tudo indefinido. Falta dizer o que testar, quando aceitar e quando parar.',
['Guarde uma referência inicial.','Mude uma coisa por tentativa.','Só adote a mudança depois de conferir.'],
'LOOP-R','Roteiro didático do projeto RSI: executar, medir, criticar, propor, testar, validar, promover e repetir.',[
('A referência vem antes da proposta','Execute a tarefa com a orientação atual e guarde o resultado. Defina uma medida simples, ligada ao objetivo. Só depois peça uma proposta. Sem referência inicial, uma resposta convincente pode parecer melhor por novidade. Mantenha os mesmos casos na comparação.', 'gestora|Marina registra se cada resposta informa horário, evita promessas sem base e indica a próxima ação.', 'Sem referência','A nova resposta parece excelente.','Com referência','A antiga cumpriu dois critérios; a nova será avaliada pelos mesmos critérios.'),
('Teste uma mudança de cada vez','Criticar significa localizar uma falha observável. Propor significa sugerir uma alteração que possa corrigi-la. Testar significa executar de novo em condições comparáveis. Se você mudar instrução, modelo e exemplos juntos, fica difícil atribuir o resultado a uma causa.', 'educador|Ícaro acrescenta apenas “cite o trecho de apoio”. Mantém o texto, a quantidade de questões e os critérios anteriores.', 'Mudanças misturadas','Trocar tudo e comparar a impressão geral.','Mudança isolada','Acrescentar uma regra e contar perguntas apoiadas no texto.'),
('Validar e adotar são decisões distintas','Validar confere se o ganho resiste a casos reservados. Promover significa passar a usar a versão aprovada. Repetir começa um novo ciclo, com registro e limite. Uma candidata pode ganhar no ensaio e perder na validação. Nesse caso, mantenha a versão anterior.', 'gestora|Marina confere novas perguntas antes de guardar a orientação. Se ela inventar um prazo, a candidata não entra em uso.', 'Ensaio','A candidata passou nos exemplos usados para melhorar.','Validação','A candidata também precisa passar em exemplos reservados.')],
'Escreva seu primeiro LOOP-R',
'Tarefa: responder dúvidas sobre horário. Alternativa escolar: criar questões a partir de um texto.\nExecutar: guardar a resposta atual.\nMedir: escolher dois critérios.\nCriticar: apontar uma falha.\nPropor: alterar uma instrução.\nTestar: comparar nos mesmos casos.\nValidar: usar casos reservados.\nPromover: decisão humana.\nRepetir: no máximo três rodadas neste ensaio.',
['Preencha as oito etapas no papel ou nas notas.','Indique a única mudança da primeira tentativa.','Defina uma condição de parada e quem decide.'],
'Um ciclo completo diz como a comparação ocorre e quem aceita a candidata. “A IA achou melhor” não substitui os critérios escolhidos.',
('A candidata melhorou no ensaio. Qual é o próximo passo?','Validar em casos reservados.','Substituir tudo imediatamente.','Apagar a versão anterior.'),
[('Você mudou três componentes e ganhou qualidade. Qual dúvida permanece?','Qual alteração contribuiu para o ganho e quais foram desnecessárias.'),('O que fazer com uma candidata pior?','Registrar a tentativa e manter a referência aprovada.'),('Por que escrever o limite antes de começar?','Para evitar tentativas indefinidas e comparações escolhidas depois do resultado.')],
('O nome e a contribuição do projeto','LOOP-R e IA Cultivada são expressões do material conceitual do projeto. São usadas aqui como organização didática. Não são protocolos científicos padronizados. Seu valor prático está na disciplina de medir e preservar histórico. Uma implantação automatizada exige também controles técnicos, avaliação independente e manutenção. A atividade desta aula pode ser feita integralmente com papel.'),['dgmp'])

aula('Separe quem propõe, quem mede e quem aprova',
'definir responsabilidades e permissões para um pequeno sistema de melhoria.',
'Se a mesma IA escreve a resposta e declara que está perfeita, falta uma conferência confiável. Dividir papéis torna os erros mais visíveis.',
['O proponente sugere mudanças.','O avaliador confere critérios fixados antes.','Uma pessoa autoriza a adoção.'],
'avaliador','Pessoa ou mecanismo que aplica critérios de qualidade a um resultado. Precisa de evidência, não só de opinião.',[
('Defina entradas e saídas de cada papel','Um proponente recebe a tarefa, os erros observados e os limites. Ele devolve uma candidata e a justificativa. O avaliador recebe casos e critérios, e devolve resultados conferíveis. Quem aprova examina qualidade, custo e efeitos indesejados antes de decidir.', 'educador|Ícaro pede uma nova instrução à IA, confere perguntas com o texto e decide se usará a instrução.', 'Proposta','Trocar “crie questões” por “crie questões respondíveis pelo trecho”.','Avaliação','Para cada questão, apontar onde o texto contém a resposta.'),
('Duas conversas não garantem independência','Separar telas ajuda a organizar o trabalho, mas os modelos podem repetir os mesmos erros. Use critérios verificáveis e exemplos que a proposta não recebeu. Para afirmações factuais, confira a referência. Para resultados subjetivos, registre divergências em vez de escondê-las numa nota.', 'gestora|Marina pede a outra conversa uma crítica. Mesmo assim, compara o horário com o documento da loja.', 'Conferência frágil','Outra IA disse que ficou ótimo.','Conferência útil','O horário corresponde ao documento e a resposta não inventou prazo.'),
('Permissões seguem a tarefa','Quem propõe não precisa alterar a regra de avaliação. Quem avalia não precisa enviar mensagens reais. Defina o que cada papel pode ler e modificar. Se surgir uma ação fora do combinado, pare e revise. Comece com cópias de treino, sem ações externas.', 'educador|A rotina de Ícaro prepara rascunhos. Ela não pode mudar notas nem comunicar famílias.', 'Permitido no ensaio','Ler texto fictício e produzir rascunhos.','Fora do ensaio','Alterar notas ou enviar mensagens a pessoas.')],
'Monte uma ficha de responsabilidades',
'No papel ou nas notas, faça três linhas: proponente, avaliador, responsável final.\nPara cada linha, registre: recebe; produz; pode alterar; não pode alterar.\nCaso da loja: rascunhos de atendimento.\nCaso da escola: rascunhos de questões.\nA regra de avaliação fica fora do alcance do proponente.',
['Preencha entradas e saídas dos três papéis.','Separe proposta de autorização.','Indique uma ação que encerra o ensaio.'],
'A pessoa responsável autoriza a adoção. A ferramenta pode sugerir e organizar evidências. Não deve controlar sozinha a resposta, o gabarito e a decisão.',
('Duas IAs concordaram sobre um horário. O que decide?','A referência vigente.','A quantidade de concordâncias.','A resposta mais confiante.'),
[('O proponente pode reescrever seu próprio gabarito?','Não nesse desenho; isso compromete a comparação.'),('Uma terceira conversa elimina erros compartilhados?','Não. A referência e os testes continuam necessários.'),('Quem precisa autorizar a passagem para uso real?','O responsável definido na ficha, com as evidências da comparação.')],
('Da ficha ao sistema técnico','Quando uma equipe automatizar o desenho, precisará transformar limites escritos em permissões reais. Papéis separados no pedido não impedem acesso indevido. A equipe deve controlar arquivos, ferramentas e ações disponíveis. Também precisa registrar falhas e preservar os critérios de avaliação. Esta aula produz a especificação do trabalho, não uma implementação isolada e segura por si só.'),['dsec','tamper'])

aula('Guarde experiências, inclusive as que falharam',
'criar um registro que permita repetir uma tentativa e recuperar a versão anterior.',
'Sem histórico, a próxima conversa repete os mesmos erros. Guardar tudo sem organização também não ajuda: fica difícil saber qual versão vale.',
['Cada tentativa tem hipótese e resultado.','Falhas explicadas evitam repetir trabalho.','A versão aprovada continua identificável.'],
'memória de experimentos','Registro de tentativas, condições, resultados e decisões. Permite aprender com o histórico sem tratar toda tentativa como regra.',[
('Uma experiência precisa ser repetível','Anote a tarefa, o material usado, a instrução e a data. Registre também a versão da ferramenta quando ela estiver disponível. Guarde o resultado completo antes de resumir. Uma frase como “funcionou melhor” não permite repetir a experiência nem entender seu limite.', 'gestora|Marina salva as duas respostas e os casos usados. Outra pessoa consegue reaplicar os critérios sem adivinhar o que aconteceu.', 'Registro vago','Versão nova: melhor.','Registro útil','Mudança: pedir informação faltante. Casos: A, B, C. Resultado: não inventou horário.'),
('Falha é informação com contexto','Descreva o que falhou e a menor correção a testar. Evite generalizações como “esse modelo não serve”. Uma tentativa pode falhar por falta de referência, critério ambíguo ou execução incompleta. Diferenciar essas causas evita uma troca desnecessária do sistema inteiro.', 'educador|Ícaro registra que uma pergunta usava conteúdo ausente. A próxima tentativa exige um trecho de apoio para cada resposta.', 'Sintoma','Questão exige informação que não aparece no texto.','Correção proposta','Pedir a frase de apoio e descartar questões sem evidência.'),
('Histórico não é autorização','Guarde candidatas separadas da orientação vigente. Uma versão experimental pode ser útil depois, mas não deve entrar em uso por engano. Identifique a aprovada e mantenha uma cópia anterior. Defina quando reavaliar, especialmente após mudanças de conteúdo ou ferramenta.', 'gestora|Marina mantém “orientação vigente” e “tentativas”. A equipe consulta somente a primeira para atender.', 'Uso atual','Versão aprovada, data e responsável.','Arquivo de tentativas','Candidatas, resultados e motivos de rejeição.')],
'Registre uma tentativa completa',
'Copie no bloco de notas:\nData:\nTarefa e material:\nOrientação anterior:\nHipótese:\nÚnica mudança:\nCasos e critérios:\nResultado observado:\nDecisão e responsável:\nVersão que continua vigente:\nQuando revisar:',
['Preencha com uma tentativa fictícia da loja ou da escola.','Inclua uma falha e a menor correção proposta.','Peça a alguém, ou confira você mesmo, se o registro permite repetir o teste.'],
'Uma boa ficha contém material, mudança e evidência. O rótulo “aprovada” depende de uma decisão registrada, não do nome escolhido pela IA.',
('A candidata foi rejeitada. O que vale guardar?','Resultado e motivo.','Somente as vitórias.','A candidata como regra atual.'),
[('Qual registro ajuda a repetir um teste?','Material, instrução, ferramenta, casos, critérios e resultado observado.'),('Por que separar tentativas da orientação vigente?','Para impedir adoção acidental de uma versão não aprovada.'),('Quando um resultado antigo merece nova avaliação?','Quando mudam os materiais, a ferramenta, os casos ou as necessidades.')],
('Memória não pode virar depósito de segredos','Registre o suficiente para reproduzir a experiência, usando materiais fictícios ou autorizados. Evite copiar dados pessoais sem necessidade. Um resumo deve apontar para o registro completo, sem apagar resultados contrários. Histórico ajuda a investigação, mas não prova que a mudança seja boa. A validação continua separada da organização dos arquivos.'),['dgmp'])

aula('AlphaEvolve: um ganho numa peça tem um alcance definido',
'explicar um caso real de otimização e distinguir ganho local de ganho total.',
'Uma manchete diz que algo ficou 23% mais rápido. Antes de concluir que todo o sistema acelerou assim, descubra qual peça foi medida.',
['Uma IA propõe variantes de um programa.','Avaliadores verificam correção e desempenho.','O efeito no conjunto depende do gargalo.'],
'gargalo','Etapa que limita o desempenho do conjunto. Melhorar outra etapa pode trazer pouco ganho total.',[
('Propor e verificar trabalham juntos','O AlphaEvolve combina modelos de linguagem, avaliações automáticas e busca entre programas candidatos. Os resultados divulgados incluem otimizações computacionais. O problema precisa permitir uma avaliação confiável. Uma proposta elegante que produz respostas erradas não merece ser escolhida por ser rápida.', 'gestora|Marina faz uma analogia com o balcão: responder mais rápido não ajuda quando a informação está errada.', 'Objetivo incompleto','Reduzir o tempo a qualquer custo.','Objetivo completo','Preservar a resposta correta e então reduzir o tempo.'),
('O percentual pertence a uma medida','A DeepMind relatou aceleração de 23% em uma operação usada pelo Gemini. O efeito relatado no tempo de treinamento foi de 1%. Esses valores se referem a escalas diferentes. O caso mostra por que você deve perguntar onde o ganho aconteceu.', 'educador|Ícaro leva menos tempo para formatar questões. Ainda precisa ler o texto e conferir as respostas.', 'Peça otimizada','Operação específica: aceleração relatada de 23%.','Conjunto','Tempo de treinamento: redução relatada de 1%.'),
('Transfira a lógica, não a promessa','No seu trabalho, escolha uma tarefa cuja qualidade possa ser conferida. Defina o resultado correto antes de medir velocidade. Compare esforço total, incluindo revisão. A utilidade dessa lógica não depende de ter acesso à ferramenta de pesquisa do laboratório.', 'gestora|Marina mede o tempo entre receber a pergunta e aprovar a resposta. Não mede só o tempo que o chat leva para escrever.', 'Tempo parcial','Segundos para gerar um rascunho.','Tempo completo','Geração, conferência e correção até poder usar.')],
'Calcule o ganho do conjunto',
'Exercício fictício, no papel: preparar uma atividade leva 30 minutos. São 6 de formatação e 24 de leitura e revisão.\nUma mudança reduz a formatação para 3 minutos.\nQual é o novo tempo total? Quantos minutos foram poupados? Qual foi a redução percentual total?',
['Some as etapas antes e depois.','Divida a economia pelo tempo original.','Explique por que reduzir uma etapa pela metade não reduz tudo pela metade.'],
'O total cai para 27 minutos. A economia é 3 minutos, ou 10% de 30. O ganho local foi de 50%, mas o total foi de 10%.',
('A geração ficou rápida, mas a revisão dobrou. O que medir?','O tempo completo.','Só a velocidade de geração.','Só a resposta mais curta.'),
[('Por que um programa mais rápido pode ser rejeitado?','Porque precisa preservar correção e cumprir os demais critérios.'),('Qual dado falta num anúncio de ganho percentual?','A medida, a referência de comparação e as condições do teste.'),('O que torna uma tarefa adequada a esse tipo de busca?','Um resultado que possa ser avaliado de forma confiável.')],
('O que este caso sustenta','O caso demonstra contribuição da IA para melhorar componentes usados em computação e treinamento. Não demonstra aceleração ilimitada. Também não autoriza transferir o mesmo percentual para outra organização. A lição operacional é definir um avaliador antes de ampliar a busca. O cálculo da prática é uma analogia autoral, sem relação numérica com a experiência da DeepMind.'),['alpha'])

aula('Darwin Gödel Machine: comparar uma família de agentes',
'descrever o que a DGM altera e por que preserva diferentes candidatas.',
'A melhor tentativa de hoje nem sempre origina a melhor de amanhã. Explorar caminhos diferentes pode revelar melhorias que uma busca estreita perderia.',
['A DGM modifica o código do agente.','Mantém um arquivo de variantes.','Avalia desempenho em tarefas de programação.'],
'busca evolutiva','Exploração de variantes, com avaliação e seleção ao longo de rodadas. Não exige organismos vivos.',[
('O objeto alterado é o agente','A DGM usa modelos para propor alterações no código que organiza o agente. Isso inclui ferramentas e procedimentos de resolução. Não equivale a treinar novamente todos os parâmetros do modelo de linguagem. Identificar o objeto evita confundir melhoria de sistema com troca de modelo.', 'educador|Na analogia de Ícaro, mudar a rotina de conferência altera o trabalho. Não transforma automaticamente a formação do professor.', 'Objeto alterado','Código e procedimentos do agente.','O que não se deve concluir','Todos os parâmetros do modelo foram treinados de novo.'),
('Variantes guardadas abrem caminhos','O estudo mantém uma coleção crescente de agentes. Uma nova tentativa pode partir de variantes diferentes. Uma candidata mediana pode conter uma ideia útil para outra rodada. Preservar diversidade não significa colocar candidatas piores em uso real.', 'gestora|Marina guarda uma resposta curta e outra detalhada entre as tentativas. Nenhuma vira orientação vigente sem passar pelos critérios.', 'Exploração','Guardar uma ideia para testar outra combinação.','Uso real','Adotar somente uma versão validada.'),
('Resultado de teste não é garantia universal','Os autores relatam ganhos em avaliações de programação. O alcance depende das tarefas e condições estudadas. Também documentam casos de avaliação enganada. Por isso, uma nota isolada não encerra a investigação. Examine o resultado e o caminho usado para obtê-lo.', 'educador|Ícaro verifica se a pergunta tem resposta no texto. Uma marca “aprovado” gerada pela própria candidata não basta.', 'Nota declarada','A candidata afirma que passou.','Evidência conferível','Os critérios foram aplicados a resultados preservados.')],
'Escolha o destino das variantes',
'Exercício fictício: A responde corretamente, mas demora. B é rápida, mas inventa informação. C pede esclarecimento quando falta dado.\nNo papel, decida quais guardar para pesquisa e qual testar para uso.\nDefina um caso novo que possa reprovar cada candidata. Não aceite invenção de fatos para ganhar velocidade.',
['Separe guardar uma ideia de aprovar seu uso.','Crie um caso difícil para cada candidata.','Explique por que uma nota não substitui o resultado.'],
'A e C podem seguir para comparação. B pode ficar como registro de falha, sem entrar em uso. A decisão final depende de testes comuns e casos reservados.',
('Uma variante antiga trouxe uma ideia útil. O que fazer?','Testar a ideia novamente.','Adotar a variante sem conferir.','Apagar todas as variantes novas.'),
[('A DGM muda necessariamente os parâmetros do modelo?','Não; o trabalho apresentado modifica o agente que usa modelos.'),('Guardar uma variante permite colocá-la em produção?','Não. Exploração e adoção são decisões distintas.'),('Por que observar como o resultado foi obtido?','Porque a avaliação pode ser enganada sem resolver a tarefa pretendida.')],
('A comparação com a máquina de Gödel','A proposta teórica de Gödel usa demonstrações de benefício antes de alterações. A DGM trabalha com verificação empírica em tarefas. Essa diferença importa: passar em testes é evidência, não prova geral de que toda mudança futura será benéfica. Leia o artigo para conhecer os controles e as condições. Um relatório científico deve ser interpretado junto de suas limitações.'),['dgmp','dgm'])

aula('Pesquisa automatizada depende de infraestrutura e julgamento',
'comparar três iniciativas sem tratar toda automação como autonomia integral.',
'Produzir um artigo, executar uma experiência e escolher uma pergunta importante são capacidades diferentes. O curso agora conecta essas peças.',
['AI Scientist explora automação do trabalho científico.','DSec fornece ambientes para tarefas de agentes.','Julgamento humano ainda importa para direção e aceitação.'],
'ambiente isolado','Espaço de execução com limites definidos para uma tarefa. Sua proteção depende da implementação e das permissões.',[
('Automatizar etapas científicas não resolve toda a ciência','A Sakana relatou um trabalho do AI Scientist aceito numa oficina ligada ao ICLR 2025. A oficina aceitou participar da experiência de avaliação. Isso não equivale à aceitação na conferência principal. Um artigo aceito também não prova que toda conclusão seja correta.', 'educador|Ícaro distingue um rascunho de atividade de sua validação em sala. Cada etapa acrescenta evidência diferente.', 'Etapa automatizada','Produzir e analisar uma experiência delimitada.','Questão ainda aberta','Qualidade, reprodução e utilidade fora daquela experiência.'),
('Experimentos precisam de um lugar para acontecer','DSec é uma infraestrutura descrita pela DeepSeek para executar tarefas de agentes em escala. Preparar ambientes, controlar recursos e registrar ações são problemas concretos. Infraestrutura eficiente permite mais testes. Ela não comprova, sozinha, que um sistema escolhe boas perguntas ou melhora recursivamente.', 'gestora|Marina reserva cópias fictícias para testar respostas. Preparar a bancada facilita o trabalho, mas não decide qual resposta é boa.', 'Bancada pronta','Materiais e limites preparados para o ensaio.','Experimento útil','Pergunta clara, comparação e interpretação do resultado.'),
('Observe quem decide a direção','Relatos de pesquisa acelerada não eliminam a necessidade de escolher objetivos. Pergunte quem define a próxima experiência e quem pode interrompê-la. Contar tentativas é fácil. Medir contribuição científica exige avaliar o que cada tentativa realmente acrescentou.', 'educador|Ícaro pode gerar muitas variações de exercício. Ele continua decidindo quais atendem ao objetivo da aula.', 'Atividade','Mais rascunhos e mais tentativas.','Contribuição','Uma conclusão útil que resiste à conferência.')],
'Preencha uma comparação de iniciativas',
'Escreva três linhas: AI Scientist; DSec; pesquisa com agentes.\nPara cada uma, anote: o que faz; o que precisa receber; quem avalia; o que o exemplo não prova.\nUse as fontes abaixo. Se não localizar uma informação, escreva “não identificado”.',
['Identifique o objeto principal de cada iniciativa.','Registre uma limitação por iniciativa.','Evite preencher lacunas com informações imaginadas.'],
'AI Scientist: etapas da pesquisa. DSec: ambientes de execução. Uso interno de agentes: apoio a tarefas de pesquisadores. Nenhuma descrição basta para concluir autonomia geral.',
('Uma infraestrutura roda milhões de tarefas. O que isso mostra?','Escala de execução.','Qualidade científica garantida.','Autonomia geral comprovada.'),
[('Aceitação numa oficina equivale à conferência principal?','Não. É preciso preservar o contexto exato da avaliação.'),('O que uma bancada de experimentos não decide sozinha?','Qual pergunta vale investigar e como interpretar sua contribuição.'),('Qual pergunta fazer sobre uma pesquisa dita autônoma?','Quais decisões continuaram humanas e em quais etapas.')],
('O alcance da pesquisa recente','As fontes deste módulo cobrem funções complementares. A experiência de publicação, a infraestrutura e o relato interno de uso não formam uma prova conjunta de RSI autônoma. Não some indicadores incompatíveis. A proposta pública da OpenAI de setembro de 2026 descreve RSI totalmente autônoma como não ocorrendo naquele momento. É uma declaração da organização, não uma inspeção universal de todos os sistemas existentes.'),['science','dsec','intern','standards'])

aula('Prepare uma avaliação que a candidata ainda não viu',
'separar casos de desenvolvimento e validação com critérios observáveis.',
'Se você sempre corrige usando os mesmos exemplos, pode melhorar apenas nesses exemplos. O teste precisa revelar situações novas.',
['Desenvolvimento ajuda a ajustar.','Validação confere casos reservados.','Qualidade combina acertos, falhas e custo.'],
'casos reservados','Exemplos separados antes das mudanças e usados depois para avaliar a candidata. Não devem orientar cada revisão.',[
('Escolha casos que representem o trabalho','Inclua situações comuns, dados faltantes e pedidos fora do escopo. Defina a resposta esperada ou os critérios antes de rodar. Uma amostra pequena ensina o método, mas não comprova desempenho geral. Evite escolher apenas casos fáceis depois de ver os resultados.', 'gestora|Marina inclui uma pergunta sem data e outra fora do horário informado. Assim testa se a resposta pede esclarecimento.', 'Caso fácil','Qual o horário? Referência completa disponível.','Caso difícil','Abre no feriado? A referência não informa feriados.'),
('Guarde parte dos casos antes de ajustar','Use um grupo para melhorar a orientação. Reserve outro para conferir a versão escolhida. Depois de consultar os resultados reservados repetidamente, eles deixam de funcionar como novidade. Para decisões futuras, prepare outros casos e registre essa troca.', 'educador|Ícaro ajusta a instrução com dois textos. Um terceiro fica guardado até a comparação final.', 'Desenvolvimento','Textos vistos durante as revisões.','Validação','Texto separado antes e aberto somente para conferir.'),
('Registre mais que uma nota média','Marque critérios por caso, além de tempo e esforço de revisão. Uma média pode esconder uma falha importante. Repita tentativas quando as respostas variam. Compare as versões sob condições semelhantes. Não transforme um pequeno ensaio em promessa de precisão para qualquer tarefa.', 'gestora|Uma resposta de Marina ficou curta, mas inventou uma condição de troca. Essa falha impede aprovação mesmo com bom tempo.', 'Critério obrigatório','Nenhum prazo ou condição inventado.','Critério de preferência','Texto claro e curto quando os dados permitem.')],
'Crie seis casos fictícios',
'No papel, prepare seis perguntas sobre um horário de loja ou seis textos curtos para exercícios.\nSepare quatro para desenvolvimento e dois para validação antes de testar.\nCritérios: fiel à referência; não inventa; pede dado quando necessário.\nRegistre cada critério como passou, falhou ou não se aplica.',
['Prepare casos comuns e casos com informação ausente.','Reserve dois sem entregá-los à etapa de revisão.','Escreva o que reprova uma candidata apesar da nota média.'],
'Os casos reservados precisam ser novos para a revisão da candidata. A amostra de seis é didática; decisões reais exigem cobertura adequada ao risco e ao uso.',
('Você ajustou dez vezes olhando o teste reservado. O que mudou?','Ele deixou de ser reservado.','A validação ficou independente.','O resultado virou garantia geral.'),
[('Qual problema existe em testar só perguntas fáceis?','A avaliação deixa de representar falhas prováveis no uso real.'),('Uma média alta pode esconder o quê?','Um erro grave em um caso importante.'),('Como lidar com respostas que variam entre tentativas?','Repetir sob condições comparáveis e registrar a variação.')],
('Como interpretar medições públicas','O METR esclarece que horizonte de tarefas corresponde ao tempo humano de tarefas realizadas com certa taxa de sucesso. Não é o tempo que uma IA trabalha sozinha. As estimativas têm incerteza e variam entre domínios. Essa cautela também vale no seu ensaio: uma medida útil precisa dizer o que mede, quais tarefas inclui e quais conclusões não permite.'),['metr'])

aula('Uma nota melhor pode esconder uma tarefa pior',
'identificar três atalhos que enganam a avaliação e propor uma proteção para cada um.',
'Um sistema pressionado por uma medida pode otimizar a medida e abandonar o objetivo. Acontece quando a regra permite atalhos.',
['A medida representa apenas parte do objetivo.','O resultado precisa de evidência externa.','Quem é avaliado não deve controlar seu gabarito.'],
'manipulação da recompensa','Obter boa pontuação explorando falhas da avaliação, sem cumprir a intenção da tarefa.',[
('A meta incompleta cria atalhos','Se o objetivo for apenas responder rápido, omitir informação pode parecer uma vitória. Se for aumentar a quantidade, duplicar resultados pode parecer progresso. Escreva também o que precisa permanecer correto. Combine medida principal com critérios que impeçam essas perdas.', 'gestora|Marina não aceita mensagens vazias para reduzir tempo de atendimento. A resposta precisa resolver a dúvida ou pedir a informação faltante.', 'Meta vulnerável','Responder em poucas palavras.','Meta protegida','Responder com fidelidade e concisão, sem omitir o necessário.'),
('Declaração não é execução','Uma ferramenta pode afirmar que conferiu algo sem produzir evidência. Guarde o resultado observável da checagem. Diferencie uma simulação didática de uma execução real. Quando não houver prova suficiente, registre “não verificado”, em vez de transformar confiança em aprovação.', 'educador|Ícaro pede o trecho que sustenta cada resposta. “Todas conferidas” não substitui localizar as frases.', 'Declaração','Conferi e está tudo certo.','Evidência','Questão 2: a resposta aparece na segunda frase do texto.'),
('Proteja os critérios de mudanças convenientes','Uma candidata não deve facilitar o próprio exame. Preserve os casos, o gabarito e os resultados originais. Se uma regra estiver errada, revise-a num processo separado e reavalie todas as versões. Não altere critérios só para salvar a candidata preferida.', 'gestora|Marina descobre um critério ambíguo. Ela o corrige e aplica de novo às duas versões, sem favorecer a nova.', 'Comparação inválida','Mudar a regra depois para a candidata passar.','Comparação refeita','Corrigir a regra e testar todas as versões novamente.')],
'Encontre o atalho',
'Caso A: avaliam quantidade; a IA duplica questões.\nCaso B: avaliam rapidez; a IA omite condições essenciais.\nCaso C: pedem conferência; a IA só escreve “conferido”.\nNo papel, associe cada falha a uma proteção concreta.',
['Explique a diferença entre pontuação e objetivo.','Proponha uma checagem observável para cada caso.','Indique quem mantém os critérios fora do alcance da candidata.'],
'A: contar questões distintas e úteis. B: verificar conteúdo obrigatório além de tempo. C: exigir e conferir evidências. O responsável preserva critérios e registros.',
('A nota subiu após apagar casos difíceis. O que concluir?','A comparação foi alterada.','A capacidade aumentou muito.','Os casos difíceis eram inúteis.'),
[('Qual risco existe numa meta de quantidade?','Produzir itens duplicados ou sem utilidade para elevar a contagem.'),('Como tratar “testei e passou” sem evidência?','Como uma declaração ainda não verificada.'),('Se o critério original estava errado, como corrigir a comparação?','Revisar o critério separadamente e reavaliar todas as versões.')],
('Por que o risco não é apenas teórico','A Sakana descreveu casos de registros de testes inventados e alteração de marcadores usados na avaliação. A Anthropic estudou manipulação de recompensa em cenários controlados. Esses achados motivam conferência independente. Não significam que toda IA tenha intenção humana de enganar. O foco prático é detectar comportamentos que produzem pontuação sem cumprir o objetivo.'),['dgm','tamper'])

aula('Dados gerados precisam de origem, diversidade e conferência',
'avaliar um pequeno conjunto de exemplos fictícios antes de usá-lo para melhorar uma rotina.',
'Gerar mil exemplos é fácil. Saber se são corretos, variados e adequados ao trabalho exige uma avaliação diferente.',
['Quantidade não substitui cobertura.','Guarde referências reais autorizadas.','O juiz automático também pode errar.'],
'dados sintéticos','Exemplos produzidos artificialmente, inclusive por IA. Podem servir a testes e treinamento, com verificação adequada.',[
('Comece pelo que os exemplos representam','Escolha categorias necessárias para a tarefa. Inclua situações comuns e exceções relevantes. Marque quais exemplos foram gerados e quem os conferiu. Uma coleção de variações quase iguais aumenta o volume sem ampliar muito a cobertura.', 'educador|Ícaro percebe que dez questões geradas pedem a mesma informação. Troca parte delas por perguntas que avaliam outras ideias do texto.', 'Volume','Dez versões da mesma pergunta.','Cobertura','Perguntas sobre diferentes pontos e uma com informação ausente.'),
('Não alimente o ciclo apenas com suas próprias saídas','Estudos mostram degradação em certas condições de treino recursivo com dados gerados. Isso não significa que todo dado sintético cause colapso. A composição, a seleção e a preservação de diversidade importam. Não substitua referências conferidas por respostas geradas sem verificar.', 'gestora|Marina usa o documento de horário como referência. Não trata uma resposta antiga do chat como a fonte oficial.', 'Referência perdida','Respostas novas aprendem apenas com respostas antigas.','Referência preservada','Cada exemplo é conferido contra material autorizado.'),
('Avaliação por IA é uma ajuda limitada','Uma IA pode comparar resultados e localizar problemas. Mas pode preferir textos longos ou concordar com erros plausíveis. Confira uma amostra humana e critérios objetivos. Quando o julgamento for incerto, preserve a divergência em vez de fabricar uma conclusão.', 'educador|Ícaro usa a crítica automática para localizar questões suspeitas. Ele confere o texto antes de aceitar a avaliação.', 'Uso assistido','A IA aponta possíveis problemas.','Decisão conferida','A pessoa verifica referência, cobertura e adequação.')],
'Audite cinco exemplos',
'Crie ou escreva cinco perguntas fictícias sobre um texto curto.\nAnote para cada uma: origem; ideia avaliada; resposta sustentada; repetição; informação ausente.\nSubstitua uma pergunta repetida por outra que teste um ponto diferente.\nNão use dados pessoais de alunos ou clientes.',
['Identifique exemplos gerados e referências usadas.','Conte ideias distintas, além da quantidade.','Corrija um problema e registre o motivo.'],
'Uma coleção melhor cobre situações relevantes e preserva respostas verificáveis. O número de exemplos sozinho não informa essa qualidade.',
('Cem exemplos repetem o mesmo erro. O que fazer?','Corrigir a referência e revisar.','Gerar mais do mesmo.','Aceitar pela grande quantidade.'),
[('Dados sintéticos são sempre inadequados?','Não. Sua utilidade depende da origem, seleção, diversidade e validação.'),('O que uma IA julgadora pode reproduzir?','Vieses e erros compartilhados com quem gerou as respostas.'),('Qual registro ajuda a avaliar um exemplo gerado?','Origem, referência, critério e conferência realizada.')],
('Duas linhas de pesquisa diferentes','O estudo de colapso analisa perda de informação em treino recursivo com dados gerados. O trabalho de modelos que se autorrecompensam investiga usar o próprio modelo para produzir sinais de avaliação. São problemas distintos. Resultados promissores em um deles não eliminam os riscos do outro. Para o seu ensaio, preserve referências e nunca confunda uma preferência automática com verdade factual.'),['collapse','reward'])

aula('Atendimento: melhorar sem inventar uma política',
'comparar duas instruções de atendimento usando uma política fictícia e perguntas reservadas.',
'Uma resposta educada pode prometer algo que a empresa não oferece. O ciclo precisa melhorar a utilidade sem inventar compromissos.',
['A política é a referência.','Perguntas sem resposta exigem esclarecimento.','Você aprova o rascunho antes de usar.'],
'fidelidade','Correspondência entre a resposta e a referência disponível. Uma resposta fiel não acrescenta fatos sem apoio.',[
('Forneça uma referência pequena e completa','Use uma política fictícia para aprender o método. Delimite quais informações estão disponíveis. Peça que a resposta reconheça lacunas. Uma instrução de tom cordial não substitui os fatos. O primeiro teste deve revelar se o sistema distingue informação conhecida de desconhecida.', 'gestora|Marina testa uma papelaria imaginária. A referência informa horário e retirada, mas não informa prazo de troca.', 'Referência do exercício','A loja abre das 9h às 18h. Retirada após aviso. Não há informação sobre trocas.','Pergunta do cliente fictício','Posso trocar depois de dez dias?'),
('Melhore apenas a orientação de resposta','Compare uma instrução básica com outra que exige indicar dados ausentes. Mantenha o modelo e a referência. Use conversas separadas ou identifique claramente cada tentativa. Se a ferramenta não estiver disponível, faça a comparação manual dos rascunhos fornecidos.', 'educador|Ícaro aplica a mesma lógica a avisos escolares. Uma ausência de informação não vira autorização imaginada.', 'Rascunho inadequado','Sim, a troca é permitida em dez dias.','Rascunho fiel','A referência não informa o prazo de troca. Confirme a política com a loja.'),
('Valide com uma pergunta diferente','Depois de ajustar a instrução, teste uma pergunta reservada. Procure fatos inventados e ações confusas. Registre também se a resposta resolve o que pode resolver. Dizer “não sei” para tudo evita invenções, mas pode tornar o serviço inútil.', 'gestora|Marina pergunta quando pode retirar um pedido. A resposta deve usar a condição disponível: após o aviso.', 'Pergunta reservada','Posso retirar agora?','Resposta sustentada','A retirada ocorre após o aviso. Você já recebeu esse aviso?')],
'Faça uma rodada no chat ou no papel',
'Use somente esta referência fictícia: abre das 9h às 18h; retirada após aviso; trocas não informadas.\nVersão A: responda cordialmente à pergunta.\nVersão B: responda usando só a referência; se faltar dado, explique e peça confirmação.\nDesenvolvimento: Qual o horário? Posso trocar em dez dias?\nReserve para conferir depois: Posso retirar agora?\nCompare fidelidade, utilidade e tempo de revisão.',
['Produza ou escreva respostas com A e B para os casos de desenvolvimento.','Teste a candidata na pergunta reservada sem ajustar depois.','Registre acertos, falhas e a decisão sobre a candidata.'],
'A resposta sobre troca não pode criar prazo. A resposta sobre retirada deve perguntar pelo aviso. Se uma candidata falhar, guarde o resultado e não a aprove.',
('A IA não inventa, mas recusa até informar o horário. Qual problema existe?','Perda de utilidade.','Fidelidade perfeita em tudo.','Recursão comprovada.'),
[('A política não contém um prazo. Qual resposta é adequada?','Explicar a lacuna e pedir confirmação, sem criar a regra.'),('Por que guardar uma pergunta para o fim?','Para conferir se a candidata funciona além dos casos usados no ajuste.'),('O que deve ser revisado antes de usar a mensagem?','Os fatos, as condições e os compromissos que o texto cria.')],
('Do exercício ao trabalho','A política do exercício foi inventada para ensino. Ela não descreve uma empresa real nem estabelece direitos do consumidor. Para uso profissional, troque-a pela referência autorizada da organização e mantenha uma pessoa responsável pela revisão. Não use o exercício como aconselhamento jurídico. A melhoria demonstrada é local e supervisionada, sem treinamento de um novo modelo.'),['tamper'])

aula('Educação: produzir questões que o texto sustenta',
'criar e conferir três questões com respostas apoiadas em um texto curto.',
'Uma questão pode parecer boa e cobrar algo que o aluno não recebeu. O objetivo é conferir o vínculo entre texto, pergunta e resposta.',
['Defina o objetivo de aprendizagem.','Peça a frase que sustenta cada resposta.','O educador decide a adequação da atividade.'],
'critério de qualidade','Regra observável para decidir se o resultado atende ao objetivo. Deve ser definida antes de comparar versões.',[
('Diga o que o aluno deve demonstrar','Escolha uma habilidade pequena, como localizar informação explícita. Não misture esse objetivo com pesquisa externa sem avisar. Forneça o texto e a quantidade de questões. A avaliação precisa corresponder à habilidade escolhida, não apenas à aparência de uma atividade escolar.', 'educador|Ícaro quer que a turma localize condições de reciclagem. Ele usa um texto curto e dispensa conhecimento externo.', 'Texto fictício','Papel limpo pode ser reciclado. Papel com gordura deve ser separado. A coleta ocorre na terça-feira.','Objetivo','Localizar informações que aparecem explicitamente no texto.'),
('Peça evidência junto da resposta','Solicite pergunta, resposta e trecho de apoio. Confira se o trecho realmente sustenta a resposta. Copiar qualquer frase não resolve. Exija que a ferramenta descarte questões sem apoio no material. Você pode aplicar esse procedimento à mão, sem depender de um chat.', 'gestora|Marina usa a mesma lógica num treinamento da equipe. Cada pergunta deve remeter à orientação que foi entregue.', 'Questão sem apoio','Quantas toneladas a coleta recolhe por mês?','Questão sustentada','Em que dia ocorre a coleta? Resposta: terça-feira. Apoio: a última frase.'),
('Confira variedade e adequação','Três questões quase iguais não avaliam três ideias diferentes. Confira repetição, clareza e dificuldade. A ferramenta pode sugerir uma revisão, mas não conhece automaticamente a turma. Para uma próxima rodada, use outro texto reservado e mantenha os mesmos critérios.', 'educador|Ícaro rejeita duas perguntas que pedem o mesmo dia. Ele acrescenta uma pergunta sobre a condição do papel.', 'Cobertura limitada','Três perguntas sobre a terça-feira.','Cobertura ampliada','Condição do papel limpo, separação do engordurado e dia da coleta.')],
'Produza uma atividade verificável',
'Texto fictício: Papel limpo pode ser reciclado. Papel com gordura deve ser separado. A coleta ocorre na terça-feira.\nCrie três questões para localizar informações explícitas.\nPara cada uma, forneça resposta e a frase exata de apoio.\nCubra três informações diferentes. Não acrescente conhecimento externo.\nRevise cada vínculo entre pergunta, resposta e trecho.',
['Escreva ou peça três questões usando o molde.','Marque quais têm apoio real e quais repetem a mesma ideia.','Revise uma questão problemática e guarde antes e depois.'],
'As três informações disponíveis são a condição do papel limpo, a separação do papel com gordura e o dia da coleta. Tonelagem não aparece.',
('A questão cita uma frase, mas ela não responde à pergunta. O que fazer?','Revisar ou descartar.','Aceitar porque há citação.','Aumentar a nota pela forma.'),
[('Por que definir a habilidade antes de gerar questões?','Para alinhar a avaliação ao que o aluno precisa demonstrar.'),('Uma citação garante uma resposta correta?','Não. É preciso conferir se o trecho sustenta a resposta.'),('Qual decisão não deve ser delegada só à aparência do texto?','A adequação da atividade ao objetivo e à turma.')],
('Melhoria do material não prova aprendizagem','O exercício verifica qualidade do material produzido. Não mede o que os alunos aprenderam. Para avaliar aprendizagem, o educador precisará observar respostas, dificuldades e contexto da turma. Também deve evitar usar dados identificáveis em experiências desnecessárias. O método de revisão ajuda a preparar a atividade; não substitui o julgamento pedagógico.'),['science'])

aula('Documentos: transformar notas em ações sem preencher lacunas',
'produzir uma lista de ações que preserve responsáveis, prazos e informações ausentes.',
'Resumos fluidos podem inventar uma data ou atribuir uma tarefa à pessoa errada. Aqui a qualidade será rastreável até a nota original.',
['Extraia apenas o que está escrito.','Marque o que falta confirmar.','Preserve o vínculo com a referência.'],
'rastreabilidade','Possibilidade de ligar cada afirmação ao material que a sustenta e ao registro de como foi produzida.',[
('Separe extração de sugestão','Extrair recupera informações presentes. Sugerir acrescenta uma possibilidade. As duas ações podem ser úteis, desde que estejam identificadas. Peça uma lista factual primeiro. Se desejar sugestões, coloque-as numa parte separada, sem apresentá-las como decisões já tomadas.', 'gestora|Marina quer transformar notas de reunião em ações. Ela não quer que a IA escolha prazos para preencher espaços vazios.', 'Nota fictícia','Marina revisará o estoque até sexta. Ícaro preparará uma atividade; o prazo ficou pendente.','Extração fiel','Marina: estoque, até sexta. Ícaro: atividade, prazo pendente.'),
('Uma lacuna é um resultado válido','Use “não informado” quando a referência não contiver o dado. Não confunda esse rótulo com falta de capacidade. Ele mostra o limite do material. Uma lista com lacunas explícitas pode ser mais útil que um resumo completo e inventado.', 'educador|Ícaro prefere receber “prazo pendente”. Assim sabe qual pergunta fazer antes de planejar a atividade.', 'Preenchimento inventado','Ícaro entregará a atividade na sexta-feira.','Lacuna preservada','O prazo da atividade de Ícaro precisa ser confirmado.'),
('Compare item por item','Avalie pessoa, ação e prazo separadamente. Conte omissões e acréscimos sem apoio. Depois confira clareza. Ao revisar a orientação, altere apenas uma regra. Mantenha a nota original disponível para que outra pessoa consiga verificar a lista.', 'gestora|Marina confere cada linha contra a nota. A revisão encontra a data indevidamente copiada de outra tarefa.', 'Critérios','Responsável correto; ação correta; prazo fiel ou ausente.','Erro detectado','Prazo de uma tarefa aplicado indevidamente à outra.')],
'Extraia e revise duas ações',
'Notas fictícias: Marina revisará o estoque até sexta. Ícaro preparará uma atividade; o prazo ficou pendente.\nProduza uma lista com responsável, ação, prazo e trecho de apoio.\nEscreva “não informado” quando faltar dado.\nNão proponha datas nem trate sugestões como decisões.\nConfira cada campo contra as notas originais.',
['Produza a lista no chat ou nas notas.','Confira os quatro campos de cada linha.','Registre uma pergunta para resolver a lacuna existente.'],
'Marina tem prazo até sexta. Ícaro não tem prazo definido. A pergunta útil é quando a atividade deverá estar pronta, sem assumir a mesma sexta-feira.',
('O resumo contém um prazo ausente na nota. Qual é a decisão?','Remover e pedir confirmação.','Manter para completar a lista.','Aceitar se parecer plausível.'),
[('Qual diferença existe entre extrair e sugerir?','Extrair recupera conteúdo presente; sugerir acrescenta possibilidades identificadas como tais.'),('Quando “não informado” é uma boa resposta?','Quando a referência realmente não contém o dado necessário.'),('Como conferir uma lista de ações?','Comparar responsável, ação, prazo e apoio com o material original.')],
('Onde usar e onde aumentar o cuidado','Esse desenho serve como ponto de partida para sínteses, listas de pendências e revisão de materiais. Documentos que orientam decisões relevantes exigem revisão proporcional ao impacto. Mantenha acesso à referência e não esconda incertezas. Se uma ferramenta mudar de comportamento, reaplique seus casos de validação antes de confiar na orientação antiga.'),['metr'])

aula('Escolha entre um ensaio manual e uma automação',
'decidir o próximo nível de implementação com base em necessidade, custo e capacidade de conferência.',
'A vontade de automatizar pode chegar antes de existir uma boa avaliação. Uma experiência pequena ajuda a decidir se vale investir.',
['Comece manualmente para conhecer os erros.','Automatize tarefas repetidas e avaliáveis.','Sistemas de pesquisa exigem equipe e infraestrutura.'],
'autonomia','Quanto um sistema pode decidir e executar sem intervenção humana. Precisa ter escopo e limites explícitos.',[
('Um chat e uma ficha bastam para começar','Nas primeiras tentativas, copie o material, compare respostas e registre resultados. Isso torna o método visível. Você aprende quais casos falham antes de ampliar a execução. Não precisa comprar uma ferramenta especial para fazer os exercícios deste curso.', 'gestora|Marina compara duas orientações numa folha. Só considera automação depois de entender quais falhas precisa detectar.', 'Ensaio manual','Poucos casos, revisão direta e custo de tempo visível.','Pergunta de decisão','A repetição frequente justifica automatizar esta parte?'),
('O próximo nível precisa de requisitos','Uma rotina automática precisa receber dados, executar propostas, avaliar e registrar. Alguém mantém os limites e trata falhas. Antes de contratar ou construir, escreva essas necessidades. O fornecedor deve mostrar como o resultado pode ser conferido e como voltar à versão anterior.', 'educador|Ícaro especifica que a rotina só prepara questões. A aprovação pedagógica continua com ele.', 'Requisito vago','Quero uma IA que melhore sozinha.','Requisito verificável','Quero comparar instruções com casos fixos e revisar candidatas antes de adotá-las.'),
('Pesquisa de fronteira não é um botão','Modificar agentes e conduzir treinamento envolve especialização, recursos e riscos adicionais. Não trate exemplos de laboratório como uma receita pronta para qualquer empresa. Escolha o menor nível que atende à necessidade. Ganhos locais podem ser úteis sem autonomia ampla.', 'gestora|Marina não precisa construir um laboratório para reduzir erros de atendimento. Primeiro valida a orientação usada nos rascunhos.', 'Necessidade local','Melhorar uma tarefa repetida e delimitada.','Projeto de pesquisa','Investigar novos métodos com infraestrutura e avaliação especializada.')],
'Escreva uma recomendação de implementação',
'Escolha um caso: loja recebe poucas dúvidas semanais; escola prepara atividades recorrentes; equipe pesquisa novos agentes.\nAnote: frequência; medida de qualidade; quem revisa; recursos disponíveis; custo de falhar.\nRecomende ensaio manual, rotina automática limitada ou projeto de pesquisa.\nIndique qual evidência mudaria sua recomendação.',
['Relacione o nível escolhido à necessidade.','Inclua manutenção e revisão na decisão.','Defina uma condição para subir ou reduzir a autonomia.'],
'Pouca repetição costuma favorecer um ensaio manual. Uma rotina delimitada exige avaliação e manutenção. Pesquisa de agentes demanda especialização além deste curso.',
('Ainda não existe critério de qualidade. Qual é o próximo passo?','Definir e testar critérios.','Aumentar a autonomia.','Comprar mais capacidade.'),
[('Qual é uma razão concreta para automatizar?','Repetição suficiente, tarefa delimitada e avaliação confiável.'),('O que deve entrar numa especificação para uma equipe técnica?','Entradas, saídas, avaliação, permissões, limites, registro e reversão.'),('Quando reduzir autonomia?','Quando os erros não são detectáveis, o contexto muda ou a revisão não acompanha.')],
('Como conversar com quem vai implementar','Leve sua ficha de experimento e exemplos de falha. Peça uma demonstração com seus casos autorizados, incluindo os difíceis. Solicite evidência de controle de custos e interrupção. Não aceite apenas uma demonstração escolhida pelo fornecedor. A decisão depende da tarefa e das condições reais, não de um ranking geral de modelos.'),['dsec','epoch'])

aula('Planeje um piloto com orçamento e condições de parada',
'preencher um plano de piloto com objetivo, medida, responsável, teto e reversão.',
'Uma melhoria pequena pode custar mais que o benefício. Sem limite escrito, tentativas se acumulam e a decisão fica para depois.',
['Conte geração, revisão e correções.','Defina teto antes da primeira tentativa.','Pare quando faltar evidência ou controle.'],
'condição de parada','Evento que encerra o ensaio, como atingir o teto de tentativas, ultrapassar custo ou detectar uma falha crítica.',[
('Calcule o custo do resultado utilizável','Some tempo de preparação, execução e revisão. Se houver cobrança por uso, registre o valor observado. Não confunda preço anunciado com custo total do trabalho. Compare economia recorrente com esforço de preparar e manter a mudança.', 'gestora|Marina estima quanto tempo poupa por resposta e quanto gastou preparando o teste. Uma melhora rara pode não compensar a preparação.', 'Exercício fictício','Preparar o piloto: 40 minutos. Economia por uso: 2 minutos.','Ponto de equilíbrio','São necessários 20 usos para recuperar 40 minutos, sem contar manutenção.'),
('Escreva limites simples e verificáveis','Para um primeiro ensaio, escolha poucos casos e até três candidatas. Reserve um período de trabalho. Defina um teto financeiro se a ferramenta cobrar. Registre separadamente exemplos didáticos e valores realmente medidos. Não transfira o orçamento do exercício para qualquer projeto.', 'educador|Ícaro reserva uma sessão para comparar instruções. Se faltar tempo para conferir, não aprova a candidata por pressa.', 'Teto do exercício','Três candidatas, seis casos e uma sessão planejada.','Regra de decisão','Sem validação concluída, manter a versão anterior.'),
('A reversão faz parte do plano','Guarde a orientação anterior e indique quem pode restaurá-la. Pare diante de informação inventada relevante, ação não autorizada ou custo acima do teto. Investigue a falha antes de repetir. Se o sistema mudar, reavalie as condições do piloto.', 'gestora|Marina conserva a orientação vigente. Uma candidata que cria compromissos indevidos é rejeitada antes de chegar à equipe.', 'Parada','Falha obrigatória, custo excessivo ou tentativa fora do escopo.','Retorno','Continuar usando a versão anterior enquanto a causa é analisada.')],
'Preencha o plano de uma página',
'Objetivo:\nTarefa e material fictício:\nReferência inicial:\nCritérios obrigatórios:\nCasos reservados:\nAté três candidatas:\nTempo disponível e teto de gasto:\nQuem avalia e quem aprova:\nQuando parar:\nComo voltar à orientação anterior:\nQuando revisar o piloto:',
['Preencha todos os campos com um caso da loja ou da escola.','Calcule um ponto de equilíbrio com números explicitamente estimados.','Inclua uma condição que rejeite a candidata apesar de um ganho de velocidade.'],
'O plano deve permitir dizer “não aprovar” com clareza. O cálculo de 20 usos é apenas o exercício fornecido; manutenção e mudanças podem elevar esse número.',
('O orçamento acabou antes da validação. O que fazer?','Parar e manter a referência.','Aprovar pelo esforço investido.','Continuar sem registrar custos.'),
[('Qual custo costuma ficar escondido numa demonstração?','Preparação, revisão, correções e manutenção.'),('Por que guardar a versão anterior?','Para continuar o trabalho ou reverter uma mudança problemática.'),('Um ganho de velocidade compensa qualquer falha?','Não. Critérios obrigatórios não devem ser trocados por conveniência.')],
('Governança proporcional ao ensaio','O piloto deste curso não envia mensagens, não modifica sistemas externos e não usa dados pessoais. Mesmo assim, precisa de responsável e critérios. Em projetos reais, aumente os controles conforme o impacto e a autonomia. Propostas de padrões internacionais discutem supervisão e evidências; não substituem as obrigações concretas da sua organização.'),['standards','epoch'])

aula('Projeto final: compare, decida e explique o limite',
'entregar um pequeno relatório de melhoria com comparação, decisão e limites explícitos.',
'O resultado final não precisa ser uma candidata aprovada. Descobrir que uma mudança não vale a pena também é uma conclusão útil.',
['Compare a referência com uma candidata.','Use casos que ficaram reservados.','Relate ganhos, falhas e incertezas.'],
'validação','Conferência da candidata com critérios definidos e casos reservados, antes da decisão de uso.',[
('Escolha uma tarefa delimitada','Use atendimento, questões de leitura ou extração de ações. Se não fez as práticas anteriores, copie um dos materiais fictícios deste módulo. Escreva a referência inicial e uma alteração. Você pode realizar o ensaio com um chat ou comparar rascunhos manualmente.', 'educador|Ícaro escolhe questões respondíveis pelo texto. Sua única mudança será exigir um trecho de apoio.', 'Referência','Crie três questões sobre o texto fornecido.','Candidata','Crie três questões e apresente a frase que sustenta cada resposta.'),
('Execute e registre a comparação','Aplique ambas as orientações aos mesmos casos. Preserve as respostas, os critérios e os tempos observados. Depois use os casos reservados sem continuar ajustando a candidata. Se houver variação, registre-a. Uma diferença pequena num ensaio curto pode ser inconclusiva.', 'gestora|Marina testa perguntas comuns e lacunas. Ela guarda uma resposta pior junto das melhores, para não selecionar só vitórias.', 'Registro completo','Caso; versão; resposta; critérios; revisão; tempo.','Registro insuficiente','Uma captura da melhor resposta, sem comparação.'),
('A decisão precisa caber na evidência','Conclua: aprovar para uso limitado, rejeitar ou investigar mais. Explique por quê. Diga o que o experimento não demonstrou. Uma melhoria supervisionada de instrução não prova RSI autônoma. A competência final é desenhar e julgar ciclos com clareza, inclusive quando o resultado é negativo.', 'educador|Ícaro aprova apenas o uso em rascunhos revisados. Ele não afirma ter comprovado melhoria de aprendizagem dos alunos.', 'Decisão delimitada','Usar para preparar rascunhos com revisão humana.','Limite declarado','O ensaio não mede aprendizagem nem autonomia geral.')],
'Entregue seu relatório curto',
'No papel ou nas notas, complete:\n1. Tarefa, referência e material fictício.\n2. Hipótese e única mudança.\n3. Casos de desenvolvimento e casos reservados.\n4. Resultados das duas versões, incluindo falhas.\n5. Tempo e custo observados, ou “não medido”.\n6. Decisão, responsável e reversão.\n7. O que foi demonstrado e o que permanece em aberto.\nSe precisar de mais tempo para executar, divida o projeto em duas sessões.',
['Execute uma comparação pequena ou use os rascunhos didáticos, identificando a escolha.','Conclua a validação e escreva uma decisão sustentada.','Revise o relatório para separar observação, estimativa e hipótese.'],
'Qualquer das três decisões pode ser correta. O relatório passa quando preserva comparação, critérios, resultados e limites. Se usou rascunhos fornecidos, declare análise didática, não execução de IA.',
('A candidata não trouxe ganho confiável. Qual conclusão é válida?','Manter a versão anterior.','Ocultar os resultados ruins.','Afirmar sucesso para concluir.'),
[('O que diferencia um relatório de uma demonstração escolhida?','A presença de comparação, casos, critérios, falhas e limites.'),('Se você não mediu custo, como preencher o relatório?','Escrever “não medido”, sem inventar precisão.'),('Qual capacidade você leva deste curso?','Organizar, avaliar e explicar um ciclo de melhoria supervisionada.')],
('Depois do curso','Aprofunde uma frente por vez: avaliação, ferramentas, dados ou pesquisa automatizada. Reaplique o método a uma tarefa com frequência suficiente para justificar o esforço. Consulte os documentos primários antes de adotar novas alegações. O campo muda rapidamente; preserve o hábito de perguntar o que mudou, como foi medido e quem consegue conferir. A pasta de pesquisa do curso registra a data de corte e as fontes usadas.'),['dgmp','metr','epoch'])

# Ajustes após leitor simulado: casos completos, prática independente e validação separada.
AULAS[1]['promessa']=AULAS[1]['promessa'].replace('quatro formas','três formas')
AULAS[2]['molde']='Caso fictício, fornecido para a prática.\nTítulo: Teste da Escola Aurora. Autora: equipe pedagógica. Data: 25/09/2026.\nA equipe comparou duas instruções nos mesmos cinco textos.\nA instrução antiga gerou três questões com apoio correto. A nova gerou quatro.\nCada instrução foi executada uma vez. Não houve teste com alunos.\nPreencha: título; data; autores; afirmação; medida; comparação; limite.\nDepois, opcionalmente, aplique a ficha a uma fonte real do complementar.'
AULAS[2]['checks']=['Localize no caso os dados de título, autoria e data.','Registre a comparação de três com quatro questões apoiadas.','Explique por que isso não mede aprendizagem dos alunos.']
AULAS[2]['gabarito']='Título: Teste da Escola Aurora. Data: 25/09/2026. Autoria: equipe pedagógica fictícia. Medida: questões apoiadas no texto. Comparação: três contra quatro. Limites: cinco textos, uma execução e nenhum teste com alunos. O caso relata qualidade de questões; não mede aprendizagem.'
AULAS[3]['molde']='Referência fictícia: loja abre das 9h às 18h; feriados não informados.\nOrientação A: responda cordialmente. Resposta A à pergunta “Abre no feriado?”: “Sim, das 9h às 18h”.\nCritérios: fiel à referência; não inventar informação.\nCandidata B: use só a referência e informe quando faltar dado.\nPreencha as oito etapas do LOOP-R com esse caso.\nCaso reservado para conferir depois: “Abre no domingo?”. Domingos não estão informados.\nPlano no papel: até três rodadas; Marina decide.'
AULAS[3]['gabarito']='Executar: guardar A e sua resposta. Medir: A falha nos dois critérios. Criticar: inventou funcionamento em feriado. Propor: acrescentar a regra B. Testar: B deve dizer que feriados não foram informados. Validar: conferir domingo sem presumir abertura. Promover: Marina decide após conferir. Repetir: no máximo três rodadas. Este é um plano didático, não uma execução medida.'
AULAS[5]['molde']='Caso fechado e fictício. Data: 25/09/2026.\nReferência: loja abre das 9h às 18h; feriados não informados.\nInstrução A: responda cordialmente.\nInstrução B: use só a referência e indique informação ausente.\nPergunta: “Abre no feriado?”.\nResposta A fornecida: “Sim, das 9h às 18h”.\nResposta B fornecida: “Feriados não foram informados; confirme com a loja”.\nCritérios: fidelidade e ausência de invenção.\nNas notas, crie “RSI · tentativa 1”. Guarde referência, pergunta, instruções e respostas completas.\nRegistre hipótese, falha, resultado, decisão e quando revisar. Copie a versão anterior para “RSI · versão anterior”.'
AULAS[5]['gabarito']='Hipótese: explicitar lacunas reduz invenção. A falha porque afirma abertura não informada. B passa neste caso. Decisão: B segue para validação; ainda não foi aprovada para uso. As duas versões e os materiais ficam em “RSI · tentativa 1”; a anterior também fica em “RSI · versão anterior”. Revisar após casos reservados. Os resultados foram fornecidos para análise, não executados pelo aluno.'
AULAS[7]['molde']='Referência fictícia: loja abre das 9h às 18h; feriados não informados.\nPergunta comum: “Qual o horário?”.\nA responde corretamente em duas frases. B responde corretamente em uma frase. C pede esclarecimento e não informa o horário.\nPergunta difícil: “Abre no feriado?”.\nA informa ausência de dado. B afirma abertura. C informa ausência de dado.\nNo papel, aplique: fiel à referência; útil; não inventa.\nDecida quais variantes guardar e qual testar para uso. Crie um novo caso de validação.'
AULAS[7]['gabarito']='A passa nos dois casos apresentados e pode seguir para validação. B inventa abertura e deve ser rejeitada para uso. C preserva fidelidade, mas perde utilidade na pergunta comum. Guardar C para pesquisa não significa aprová-la. Um caso novo possível é perguntar sobre domingos, também não informados.'
AULAS[8]['molde']='Use estas fichas resumidas em português, baseadas nas fontes do complementar.\nAI Scientist: produz etapas de uma pesquisa; um artigo passou por revisão numa oficina ligada ao ICLR. A oficina cooperou com o experimento.\nDSec: prepara e executa ambientes para tarefas de agentes. O estudo descreve infraestrutura; escala não comprova qualidade científica.\nRelato interno da OpenAI: agentes apoiam tarefas de pesquisa. Pessoas definem prioridades e decidem quais resultados perseguir.\nFaça três linhas: iniciativa; função principal; evidência disponível; limite.\nConsultar os documentos completos é um aprofundamento opcional.'
AULAS[8]['gabarito']='AI Scientist: etapas científicas; avaliação de artigo numa oficina; não equivale à conferência principal. DSec: infraestrutura; relato técnico de execução; não mede descoberta científica. OpenAI: apoio à pesquisa; relato interno; não comprova autonomia integral. Quando uma ficha não descrever um avaliador, escreva “não detalhado aqui”.'
AULAS[9]['molde']='Referência fictícia: loja abre das 9h às 18h; retirada após aviso. Trocas, entrega, feriados e domingos não informados.\nUse seis perguntas prontas:\n1. Qual o horário?\n2. Posso retirar meu pedido?\n3. Vocês entregam em casa?\n4. Posso trocar em dez dias?\n5. Abre no feriado?\n6. Abre no domingo?\nNo papel, separe 1–4 para desenvolvimento e 5–6 para validação.\nDefina critérios: fiel à referência; não inventa; pede confirmação quando necessário.\nEsta aula prepara a avaliação. Não envie os casos reservados a uma revisão de instrução.'
AULAS[9]['pratica']='Prepare seis casos fictícios'
AULAS[9]['checks']=['Use as seis perguntas prontas ou adapte sem dados pessoais.','Separe as perguntas 5 e 6 antes de ajustar qualquer instrução.','Escreva a resposta esperada e uma falha que reprova cada caso.']
AULAS[9]['gabarito']='1: informar 9h às 18h. 2: verificar se houve aviso. 3 e 4: reconhecer serviço ou política não informados. 5 e 6: não presumir abertura. Invenção de fato reprova qualquer caso. Os seis exemplos ensinam o método, sem provar desempenho geral.'
AULAS[11]['molde']='Texto fictício: Papel limpo pode ser reciclado. Papel com gordura deve ser separado. A coleta ocorre na terça-feira.\nQuestões geradas fictícias:\n1. Em que dia ocorre a coleta?\n2. Qual é o dia da coleta?\n3. Como tratar papel com gordura?\n4. Papel limpo pode ser reciclado?\n5. Quantas toneladas são recolhidas?\nNo papel, marque origem, apoio, repetição e informação ausente.\nSubstitua a pergunta 2 por “Que condição do papel exige separação?”. Compare com a pergunta 3 para discutir redundância.\nDecida se é melhor ficar com três questões distintas, em vez de cinco.'
AULAS[11]['gabarito']='1 e 2 repetem a mesma ideia. 3 e 4 têm apoio. 5 exige informação ausente. A substituição proposta ainda se aproxima de 3. Uma decisão válida é manter apenas 1, 3 e 4. Mais questões não garantem cobertura melhor.'
AULAS[11]['quiz']=('Cem exemplos repetem o mesmo erro. O que fazer?','Conferir e corrigir exemplos.','Gerar mais do mesmo.','Aceitar pela grande quantidade.')
AULAS[12]['molde']='Copie apenas este bloco para a etapa de desenvolvimento.\nReferência fictícia: abre das 9h às 18h; retirada após aviso; trocas não informadas.\nCompare duas orientações, sem modificá-las:\nA: responda cordialmente à pergunta.\nB: responda usando só a referência; se faltar dado, explique e peça confirmação.\nPerguntas de desenvolvimento: Qual o horário? Posso trocar em dez dias?\nMostre a resposta de cada versão para cada pergunta.\nPare depois desses casos. Não aprove a candidata ainda.'
AULAS[12]['reservado']='Somente depois de encerrar o desenvolvimento, abra uma conversa nova. Cole a referência e a orientação escolhida, sem críticas anteriores. Pergunte: “Posso retirar agora?”. Confira se a resposta pergunta pelo aviso. Não altere a candidata após ver este resultado; registre a decisão.'
AULAS[12]['semchat']='Alternativa no papel: A responde “Sim, pode retirar agora”. B responde “A retirada ocorre após aviso. Você já recebeu o aviso?”. Aplique os mesmos critérios. Registre que analisou rascunhos fornecidos, sem executar um chat.'
AULAS[13]['checks'][2]='Revise uma questão problemática. Se todas estiverem corretas, registre “sem correção necessária” e explique a conferência.'
AULAS[15]['molde']='Escolha um caso fictício com dados completos:\nLoja: 4 dúvidas por semana; política curta; Marina revisa tudo; orçamento adicional zero; respostas erradas precisam de correção antes do envio.\nEscola: 20 atividades por semana; Ícaro revisa; equipe técnica disponível por 2 horas semanais; material deve ter apoio no texto.\nPesquisa: equipe técnica dedicada; comparação de agentes; ambiente isolado e orçamento próprio; resultados avaliados por testes.\nNo papel, recomende ensaio manual, rotina limitada ou pesquisa. Justifique com frequência, avaliação, recursos e custo de falhar.\nDiga que dado você mediria antes de investir mais.'
AULAS[16]['molde']='Plano fictício para completar no papel:\nMarina prepara 20 respostas por mês. O piloto exige 40 minutos de preparação.\nEconomia estimada: 2 minutos por uso. Revisão da política: 10 minutos por mês.\nFerramenta já disponível; teto de gasto adicional: zero. Sem envio de mensagens.\nReferência: abre 9h–18h; retirada após aviso; demais informações ausentes.\nDesenvolvimento: horário, retirada, troca, entrega. Reserva: feriado e domingo.\nCritérios obrigatórios: fidelidade e ausência de invenção. Até três candidatas.\nComplete: objetivo; responsável; parada; reversão; próxima revisão.\nCalcule os usos para recuperar a preparação sem manutenção. Depois discuta o efeito dos 10 minutos mensais.'
AULAS[16]['gabarito']='Sem manutenção: 40 dividido por 2 = 20 usos. Com 20 usos mensais, economiza 40 minutos e gasta 10 de manutenção: saldo estimado de 30 minutos por mês. A preparação de 40 minutos não se recupera no primeiro mês. Marina decide; para ao inventar informação ou atingir o teto; mantém a orientação anterior. Revisão mensal. São estimativas fictícias, não resultados medidos.'
AULAS[17]['promessa']='entregar um relatório curto a partir de resultados fornecidos, com comparação, decisão e limites.'
AULAS[17]['molde']='Caminho de 10 minutos: analise os resultados fictícios abaixo. Não são medições reais.\nReferência: loja abre 9h–18h; feriados não informados.\nA: responda cordialmente. B: use só a referência e informe lacunas.\nDesenvolvimento — horário: A e B respondem 9h–18h.\nDesenvolvimento — troca: A promete dez dias; B diz que falta informação.\nReservado — feriado: A afirma abertura; B informa ausência de dado.\nTempos fictícios de revisão por caso: A = 2, 3, 3 minutos; B = 1, 1, 1 minuto. Gasto financeiro não medido.\nCritérios: fidelidade; ausência de invenção; utilidade.\nEscreva: hipótese; única mudança; comparação; falhas; tempo; decisão; responsável; reversão; limite.\nOpcional: faça depois uma execução própria em outra sessão, usando novos casos reservados.'
AULAS[17]['checks']=['Identifique o relatório como análise de resultados didáticos fornecidos.','Compare os casos e os tempos, preservando as falhas.','Escreva decisão, responsável, reversão e o que não foi demonstrado.']
AULAS[17]['gabarito']='B evita as invenções de A nos casos fornecidos. A revisão soma 8 minutos para A e 3 para B: diferença didática de 5. Gasto não medido. Decisão possível: B segue para um piloto real com revisão; Marina aprova e conserva A para reversão. Limites: dados fictícios, poucos casos, sem prova de desempenho real ou RSI autônoma.'
# Ajuda localizada no ponto de dúvida, em vez de repetir rótulos genéricos.
CALMAS={
1:'Pense no objeto alterado: foi a mensagem, a regra guardada ou o método que produz novas versões? Classifique uma mudança de cada vez.',
2:'Uma conversa nova pode não receber a regra anterior. Confira primeiro qual informação foi enviada, antes de imaginar uma mudança nos parâmetros.',
3:'Use o caso da Escola Aurora, já completo na prática. “Não informado” é uma resposta válida para um campo ausente.',
4:'Comece pela falha: a resposta inventou abertura no feriado. O gabarito mostra as oito etapas preenchidas.',
5:'Duas opiniões não mudam o horário escrito. Abra a referência vigente e compare a resposta com ela.',
6:'Copie o caso fechado da prática para as notas. Você não precisa inventar uma experiência para aprender a registrar.',
7:'Some o tempo de todas as etapas. No exercício, 3 minutos poupados pertencem a um trabalho de 30 minutos.',
8:'Guardar uma variante não significa usá-la. Confira primeiro se ela inventa fatos no caso difícil.',
9:'Use as três fichas em português da prática. Os artigos completos ficam como aprofundamento opcional.',
10:'Use as seis perguntas prontas. Separe as duas últimas antes de fazer qualquer revisão de instrução.',
11:'Pergunte se a tarefa foi cumprida mesmo sem olhar a nota. Depois procure a evidência que permitiria conferir.',
12:'Compare as perguntas 1 e 2. Elas usam palavras diferentes, mas pedem a mesma informação.',
13:'Faça somente o desenvolvimento primeiro. A validação tem um bloco separado que você abre depois.',
14:'Se as questões já estiverem corretas, não invente um defeito. Registre a conferência e preserve a versão.',
15:'O prazo de Marina não vale para Ícaro. Marque o prazo dele como não informado e formule a pergunta faltante.',
16:'Escolha um dos três casos prontos. A decisão vale para aquelas condições, não para toda empresa ou escola.',
17:'Primeiro calcule sem manutenção: 40 dividido por 2. Depois inclua o esforço mensal para ver se a conclusão muda.',
18:'Use os resultados fornecidos e diga que são didáticos. A execução de um experimento próprio é uma sessão opcional posterior.'}


# Aplicação do LOOP-R e aprovação persistente — orientação do usuário, 25/09/2026.
FONTES['loopguia']=('LOOP-R — guia do método INEMA', 'https://inematds.github.io/loop-r/guia/')
FONTES['loopcritica']=('LOOP-R — limites e viabilidade', 'https://github.com/inematds/loop-r/blob/main/docs/06-critica-e-viabilidade.md')
AULAS[3]['definicao']='Adaptação didática do método LOOP-R: executar, medir, criticar, propor, testar, validar, promover e repetir.'
AULAS[3]['steps'][2]=('Promover cria uma referência para os próximos usos',
'Validar confere a candidata em casos reservados. Aprovar autoriza sua adoção dentro de limites escritos. Promover registra essa decisão e torna a versão vigente. Nos próximos usos equivalentes, o sistema aplica a regra aprovada sem perguntar novamente. Uma nova candidata ainda precisa de avaliação e decisão.',
'gestora|Marina aprova a regra de horário para rascunhos. A equipe reutiliza essa regra enquanto a fonte e a autorização continuam válidas.',
'Antes da decisão','B é candidata: resultado bom ainda não autoriza adoção.',
'Depois da promoção','B vira a regra vigente para rascunhos. Não pedir novamente a mesma aprovação.')
AULAS[3]['gabarito']+=' Promover exige registrar versão, responsável e usos autorizados. Repetir reutiliza a regra vigente; não reinicia a aprovação da mesma regra.'
AULAS[3]['extra']=('O LOOP-R aplicado ao curso',
'O projeto LOOP-R tem agentes com papéis separados, registro de experimentos, versões e memória. No modo com revisão humana, uma mudança só é promovida após avaliação favorável e aprovação. A versão promovida passa a orientar os próximos usos. O curso aplica essa disciplina com fichas, diretamente no papel. Aprovar uma nova versão difere de reutilizar a versão vigente. O registro não prova verdade universal nem melhoria em qualquer situação. Leia também a crítica do próprio projeto.')
AULAS[3]['fontes']+=['loopguia','loopcritica']
AULAS[3]['cartoes'][2]=('Uma regra aprovada precisa da mesma aprovação em cada uso equivalente?', 'Não. Reutilize a versão vigente dentro do escopo e da validade registrados. Mudanças ou falhas exigem revisão.')
AULAS[4]['steps'][2]=('A autorização vale para um escopo escrito',
'Quem aprova define a regra, os usos permitidos e os limites. Uma autorização registrada continua valendo para usos equivalentes. Não pergunte novamente só porque começou outra execução. Mudar a regra ou ampliar suas ações exige nova decisão. Aprovar conteúdo não autoriza automaticamente envio de mensagens.',
'educador|Ícaro aprova uma regra para preparar rascunhos. O sistema reutiliza a regra, mas não altera notas nem comunica famílias.',
'Já autorizado','Preparar rascunhos com a regra aprovada, sem repetir a pergunta.',
'Fora do escopo','Enviar os rascunhos às famílias: essa ação ainda não foi autorizada.')
AULAS[4]['molde']+='\nAnote uma regra já aprovada e em quais usos ela dispensa nova aprovação.\nSepare essa regra de uma ação externa que continua sem autorização.'
AULAS[4]['gabarito']+=' A autorização registrada vale para reutilizar a mesma regra no escopo definido. Uma ação externa fora dele continua dependendo de decisão.'

AULAS[5].update(
 titulo='Transforme a aprovação em conhecimento reutilizável',
 promessa='registrar uma aprovação e distinguir reutilização, revisão e ação ainda não autorizada.',
 dor='Se o sistema pergunta tudo novamente, desperdiça decisões. Se trata qualquer aprovação como permissão ilimitada, pode repetir e ampliar um erro.',
 resumo=['Uma aprovação registrada vira conhecimento aprovado do sistema.','Reutilize dentro do escopo sem pedir a mesma aprovação.','Aprove com cuidado: uma regra errada pode orientar muitos usos.'],
 termo='conhecimento aprovado',
 definicao='Regra ou informação aceita para usos definidos, com fonte, versão, responsável e validade. A aprovação não a torna infalível.',
 steps=[
 ('Registre o que realmente foi aprovado',
 'Separe proposta, resultado de teste e regra aprovada. No LOOP-R, a promoção liga a decisão à versão vigente. Registre o conteúdo exato, a fonte, os testes e quem autorizou. Escreva para quais tarefas a aprovação vale. Sem isso, o sistema não distingue conhecimento aprovado de uma tentativa.',
 'gestora|Marina aprova a regra H1: usar o horário da política vigente em rascunhos. Feriados continuam sem informação.',
 'Tentativa guardada','H1 passou num teste, mas ainda não recebeu autorização.',
 'Conhecimento aprovado','H1, política P1, Marina, 25/09/2026. Permitido: preparar rascunhos sobre horário.'),
 ('Reutilize sem reabrir a mesma decisão',
 'Antes de usar, o sistema recupera a regra vigente e confere o escopo. Essa conferência não é um pedido de aprovação. Se tarefa, fonte e validade continuam compatíveis, ele segue sem perguntar novamente. Uma preferência aprovada pode orientar muitas respostas; cada resposta continua sujeita aos critérios combinados.',
 'educador|Ícaro aprova citar o trecho de apoio nas questões. O sistema aplica essa regra a novos rascunhos sem pedir a mesma autorização.',
 'Repetição equivalente','Outra pergunta sobre horário, com política P1 vigente: reutilizar H1.',
 'Pedido diferente','Enviar a resposta ao cliente: a aprovação para rascunhos não inclui envio.'),
 ('Aprove pensando nos próximos usos',
 'Uma aprovação pode alimentar dezenas de decisões futuras. Confira conteúdo, evidência, alcance e custo de errar antes de aprovar. Se mudar a fonte, surgir contradição ou terminar a validade, suspenda o uso afetado e revise. Revogar desativa a regra, mas preserva o histórico. Aprovação humana também pode estar errada.',
 'gestora|A política P2 muda o horário para 10h–17h. Marina suspende H1 até revisar a referência; o sistema não insiste no horário antigo.',
 'Aprovação consciente','Conheço a fonte, os testes, os usos permitidos e como revogar.',
 'Sinal de revisão','Política mudou ou apareceu erro: interromper o uso afetado e registrar o motivo.')],
 pratica='Preencha uma ficha de conhecimento aprovado',
 molde='Caso fictício. Política P1: loja abre 9h–18h; feriados não informados.\nH1: usar P1 para preparar rascunhos sobre horário, sem inventar informações.\nMarina conferiu casos de horário e feriado e aprovou H1 em 25/09/2026.\nValidade: até mudar P1, surgir erro ou Marina revogar. Envio não autorizado.\nPreencha: regra; versão; fonte; evidência; quem aprovou; data; escopo; validade; como revogar.\nClassifique: A) nova pergunta sobre horário com P1 vigente; B) P2 muda para 10h–17h; C) enviar mensagem ao cliente.\nPara cada caso, escolha: reutilizar sem perguntar; suspender e revisar; pedir autorização para nova ação.\nEscreva por que aprovar H1 exige cuidado com usos futuros.',
 checks=['Registre a aprovação com fonte, escopo, responsável e validade.','Classifique os três casos sem confundir conferência com nova aprovação.','Explique como suspender a regra e preservar sua história.'],
 gabarito='A: reutilizar H1 sem pedir novamente, após conferir P1 e o escopo. B: suspender o uso afetado e revisar com P2. C: o envio exige autorização própria. Registre decisão e versão; ao revogar H1, retire-a do uso e preserve o histórico. Uma aprovação errada pode repetir o mesmo erro. Os testes deste caso são fictícios.',
 quiz=('A regra H1 está aprovada e válida. Outra pergunta equivalente chegou. O que fazer?', 'Reutilizar dentro do escopo.', 'Pedir a mesma aprovação.', 'Ampliar todas as permissões.'),
 cartoes=[('O que a aprovação passa a representar para o sistema?', 'Conhecimento aprovado para usos definidos, registrado com fonte, versão, responsável e validade.'),('Quando dispensar nova aprovação?', 'Ao reutilizar a mesma regra vigente dentro do escopo autorizado, sem mudança relevante ou sinal de erro.'),('Por que aprovar exige consciência dos próximos usos?', 'Porque a decisão pode orientar muitas execuções. Um erro aprovado pode se repetir; registre limites e como revogar.')],
 extra=('Memória aprovada não é verdade absoluta',
 'Uma regra operacional aprovada é uma decisão de uso. Uma afirmação factual ainda depende de fontes e evidências. Não confunda os dois registros. Aprovar uma resposta isolada também não significa aprovar uma regra geral. Escreva se a decisão vale apenas para aquele resultado ou para reutilização. O sistema precisa guardar e consultar esse registro: uma conversa sem memória persistente não passa a conhecê-lo automaticamente. No LOOP-R, a versão vigente e o histórico ajudam a aplicar essa distinção. Novas candidatas passam por outro ciclo; a versão já autorizada não precisa de aprovação repetida.'),
 fontes=['loopguia','loopcritica','tamper'])
CALMAS[6]='Comece pelo caso A: nada mudou e H1 continua válida. Conferir essa validade não significa perguntar de novo a Marina.'
AULAS[12]['resumo'][2]='Aprovar uma regra não autoriza ações fora do escopo.'
AULAS[16]['molde']+='\nRegistre também: conhecimento aprovado; escopo de reutilização sem nova aprovação; validade; quem pode revogar.'
AULAS[16]['gabarito']+=' A regra promovida pode ser reutilizada sem nova pergunta dentro do escopo aprovado. Mudança de política, erro ou revogação suspende o uso afetado.'
AULAS[17]['steps'][2]=('Decida também o que poderá ser reutilizado',
 'Conclua: aprovar para uso limitado, rejeitar ou investigar mais. Se aprovar, registre o conhecimento aceito, a versão e os usos futuros autorizados. A mesma regra válida não exige aprovação a cada repetição. Novas mudanças passam por revisão. Declare o que o ensaio não provou e como suspender ou revogar a decisão.',
 'educador|Ícaro aprova uma regra para rascunhos com revisão pedagógica. Essa regra não precisa de nova aprovação a cada atividade.',
 'Conhecimento vigente','Regra B aprovada para preparar rascunhos, com fonte e versão registradas.',
 'Limite da aprovação','Não permite envio automático nem comprova melhoria de aprendizagem.')
AULAS[17]['molde']+='\nSe decidir aprovar: registre conhecimento, versão, fonte, responsável, escopo, validade e revogação.\nDiga qual uso equivalente dispensa nova aprovação e qual mudança exige revisão.'
AULAS[17]['gabarito']+=' No piloto autorizado, B vira conhecimento aprovado para preparar rascunhos, sem pedir a mesma aprovação a cada uso equivalente. A revisão das respostas permanece no escopo do piloto. Registre a fonte, a validade e quem pode suspender ou revogar.'
AULAS[17]['checks'][2]='Escreva decisão, escopo de reutilização, validade, revogação e limites.'
